### ISSUE TITLE
3.26 release plan

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/.github#5]
Let's plan the first release after GitHub migration (please fulfill this description with items TBD)

- [x] Fix the builds (https://github.com/eclipse-mylyn/.github/issues/1)
- [x] Update supported environments list (https://github.com/eclipse-mylyn/.github/issues/6)
- [x] Update version to 3.26.0 (https://github.com/eclipse-mylyn/.github/issues/7)
- [x] Create a build to promote a release (https://github.com/eclipse-mylyn/.github/issues/23)
- [x] Schedule release review (https://github.com/eclipse-mylyn/.github/issues/24)

**Comment by BeckerFrank** [comment]
The last release was a Bugfix Release 3.25.2 so I think the next release should be 3.26 instead of 3.27.
Because Oomph depends on org.eclipse.mylyn.builds it would be great if we can include this.
From my point of view we not need to include org.eclipse.mylyn.reviews and maybe also org.eclipse.mylyn. versions

**Comment by mjmeijer** [comment]
Tasks still contains the Bugzilla and Trac connectors. 
In view of "consuming our own dogwood" philosophy shouldn't we ditch the trac connector and include a Github connector?

**Comment by wimjongman** [comment]
Maarten, please create an issue for this.

**Comment by mjmeijer** [comment]
> Maarten, please create an issue for this.

Done

**Comment by BeckerFrank** [comment]
@wimjongman: I think it is time to plan how and when we should release 3.26.0.

**Comment by wimjongman** [comment]
Totally. @ruspl-afed can we release?

**Comment by ruspl-afed** [comment]
We can release when queries below will be empty (by either fixing or moving to to another milestone):
* https://github.com/eclipse-mylyn/.github/milestone/1
* https://github.com/eclipse-mylyn/org.eclipse.mylyn/milestone/1

**Comment by ruspl-afed** [comment]
Done
